controllers:
    resource: ../src/Controller/
    type: attribute

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_crypto:
    path: /crypto/{coin}
    controller: App\Controller\CryptoController::index

